### ISSUE TITLE
Težave pri prejemanju JSON podatkov

### ISSUE THREAD

**Issue by KristjanBajuk** [BloomSN/bonar#1]
Zdravo,
Nevem če je pri vas problem, ampak dobim takšen error, ko poskušam dobiti JSON podatke. 

"XMLHttpRequest cannot load http://www.bonar.si/api/restaurants. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access."

Če v chromu izklopim web security, potem dela. ( chrome.exe --user-data-dir="C:/Chrome dev session" --disable-web-security)

Zanima me, kaj bi moral narediti da bi delalo normalno, brez da izklopim varnost?

**Comment by BloomSN** [comment]
Pozdravljen, 

ravnokar preveril na Chrome in ne dobim nobene napake. Web security pa nimam izklopljen.

Različica 51.0.2704.103 (64-bit)

**Comment by KristjanBajuk** [comment]
aja pozabu sm povedat, da poskušam z Ajaxom dobit podatke. Če link odprem tudi meni deluje normalno. 

```
<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <title>READ JSON Example (AJAX)</title>
 <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
 <script type="text/javascript">
 $(document).ready(function() {
 $.ajax({
 type: "GET",
 url: "http://www.bonar.si/api/restaurants.php",
 dataType: 'json',
 crossDomain: true,
 cache: false,
 success: function(result){
 var result=result;
 console.log(result);
 $.each(result, function(i, field){
 $("#output").append("Title: "+ field.name + " address: "+field.address +" Price:"+field.price+"<br/>");
 });
 }
 });
 });
 </script>
</head>
<body>
 <div id="output">
 </div>
</body>
</html>
```

**Comment by BloomSN** [comment]
Po pravici ne vem kaj bi bila lahko napaka, preveri če ti tole kaj pomaga:

`jQuery.ajax({
    url: "http://www.bonar.si/api/restaurants.php",
    type: "GET",
})
.done(function(data, textStatus, jqXHR) {
    console.log("HTTP Request Succeeded: " + jqXHR.status);
    console.log(data);
})
.fail(function(jqXHR, textStatus, errorThrown) {
    console.log("HTTP Request Failed");
})
.always(function() {
    /* ... */
});`

**Comment by KristjanBajuk** [comment]
HTTP Request Failed dobim na firefoxu, na chormu če izklopim security je OK.

Na stackoverflow pravijo da ne podpira CORS.
 "Same Origin Policy. The second server supports CORS (Access-Control-Allow-Origin:*)." ( tu sm dal 2 linka. vašega in enega drugega ki je delal normalno )
Nevem če mate kaj več izkušenj s tem? 
http://enable-cors.org/server.html

**Comment by KristjanBajuk** [comment]
Se mogoče da ta CORS vključit na serverju?

"A webpage may contain embedded items such as a style sheet, images,JavaScript, etc and traditionally the accessing of theses items have been limited to the same domain as the page so if the page was at somedomain.com the resources allowed for that page were only form somedomain.com this is called Same-origin policy.

But for an API that doesn’t make any sense as APIs by nature have to provide data across various domains. Enter Cross-origin resource sharing (CORS), CORS allows the server to do just that but it has to be enabled on the server. But many APIs don’t have it enabled."

**Comment by BloomSN** [comment]
Preveri če je na http://test.bonar.si ok.

Če to dela lahko vklučim tudi na bonar.si

**Comment by KristjanBajuk** [comment]
Odlično, dela!

**Comment by KristjanBajuk** [comment]
Imam še eno prošnjo :D Je mogoče možno dodat regijo v JSON. ( npr. da je regija: Ljubljana ). Trenutno če bi hotel sortirati po regijah bi moral iz address dobiti podatke ven, ampak bi blo veliko bolj lažje če bi bla regija posebej. Mislim če ni preveč dela s tem. Hvala!

**Comment by BloomSN** [comment]
Ko utegnem preverim kaj bi se dalo narediti v to smer, verjetno da se naslov razreže na 2 dela in je drugi kraj.
