### ISSUE TITLE
Ne delujoča stran bonar.si

### ISSUE THREAD

**Issue by Corlex31** [BloomSN/bonar#3]
Zanima me zakaj več ne deluje stran bonar.si ?

**Comment by BloomSN** [comment]
Pozdrav,

prosim obrni se na http://flawless-code.com/#contact <http://flawless-code.com/#contact> oni so prevzeli stran.

**Comment by Corlex31** [comment]
Hvala za hiter odgovor ! lp

**Comment by trulex** [comment]
@Corlex31 a lahko prosim tu napišeš njihov odgovor ko ga prejmeš?

**Comment by Corlex31** [comment]
@trulex Še vedno nisem dobil odgovora...
